# Generated by Django 2.2 on 2019-04-09 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200)),
                ('Number', models.IntegerField()),
                ('Feedback', models.CharField(max_length=1000)),
                ('Price', models.FloatField()),
                ('Staff_of_attraction', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200)),
                ('Number', models.IntegerField()),
                ('Menu', models.CharField(max_length=100)),
                ('Feedback', models.CharField(max_length=1000)),
                ('Price', models.FloatField()),
                ('Staff_of_cafe', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200)),
                ('Number', models.IntegerField()),
                ('Feedback', models.CharField(max_length=1000)),
                ('Price', models.FloatField()),
                ('Staff_of_hostel', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200)),
                ('Number', models.IntegerField()),
                ('Staff_of_hotel', models.CharField(max_length=1000)),
                ('Price', models.FloatField()),
                ('Feedback', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_of_hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=300)),
                ('Assessment', models.IntegerField(max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_of_hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=300)),
                ('Assessment', models.IntegerField(max_length=100)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_of_cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=300)),
                ('Assessment', models.IntegerField(max_length=100)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_of_attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=300)),
                ('Assessment', models.IntegerField(max_length=100)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Attraction')),
            ],
        ),
    ]
